# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchitem',
            old_name='category',
            new_name='query_word',
        ),
    ]
