# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
