# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0004_auto_20180622_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='featured_products.Comment'),
        ),
    ]
