# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0006_auto_20180622_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
