# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0007_comment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
